[package]
name = "hello-plugin"
version = "0.0.0"
edition = "2024"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.140"
# TODO: do not depend on sdk-rust being around
wassel-sdk-rust = { path = "../../../sdk-rust/" }
