id = "rust-hello"
name = "Hello Rust Plugin"
version = "0.0.0"
component = "${CARGO_TARGET_DIR:target}/wasm32-wasip2/debug/hello_plugin.wasm"
endpoint = "/rust/hello/"

[build]
cmd = "cargo build --target wasm32-wasip2"
